### ISSUE TITLE
Architecture documentation 

### ISSUE THREAD

**Issue by keyvaann** [RADAR-base/RADAR-K8s-Infrastructure#11]
I think it would be good to have some documentation on architecture of the resources that is created by this repository.
For example I see that 2 node groups will be created during cluster creation and one is in dmz group with a public subnet and the other one in a private subnet with worker group. So I'm wondering:
- Why is this necessary? 
- Is there any changes needed to be done to RADAR-Kubernete to take advantage of it? (I can see the `taints` being defined in the dmz group)

**Comment by baixiac** [comment]
The dmz group/taints are no longer a default and have been disabled in recent releases. Assume adding taints is business-specific and should not be imposed. Think we can close this now and feel free to re-open the issue if people feel further documentation on this experimental feature is needed.
