### ISSUE TITLE
Compatibility with newer Terraform versions 

### ISSUE THREAD

**Issue by keyvaann** [RADAR-base/RADAR-K8s-Infrastructure#8]
The repository is configured to use Terraform 1.4 however now version 1.7 is about to get released. It would be good to officially support newer versions. I have created an EKS cluster via version 1.6 and other than one error didn't had other issues so it hopefully it won't be too much effort to support the newer versions.

**Comment by baixiac** [comment]
Good point. It looks TF 1.4 reached its EOL security support two months ago. Supporting 1.5 is definitely part of the next release. Before that we want to get an MVP working across multiple sites. Is it possible for you to confirm TF 1.4 works without any errors on your site?

**Comment by K1Hyve** [comment]
I can download version 1.4 in run `terraform plan`, would that be useful?

**Comment by baixiac** [comment]
If I am not misunderstanding, you found the root cause in https://github.com/phidatalab/RADAR-K8s-Infrastructure/issues/5? I don't think that test is needed any more if version 1.6 works for you. The template has been tested on TF 1.4, TF 1.5 and TF 1.6 on our site.

**Comment by keyvaann** [comment]
This is solved.
